name: Build

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

defaults:
  run:
    working-directory: ./packages/ui

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [20.16]
        pnpm: [9.7.0]
    name: 📦️ Build Node-${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: ✨ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}

      - name: 🔨 Install JavaScript dependencies
        run: pnpm install

      - name: ✅ Fix code style and build for production
        run: pnpm build

      - name: 📂 Upload Deno distribution files
        uses: actions/upload-artifact@v4
        with:
          name: deno_dist
          path: packages/ui/jsr
          overwrite: true
