name: CI

permissions:
  contents: read

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [20.16]
        experimental: [false]
    name: 👷 CI Styliz with Node-${{ matrix.node }} under ${{ matrix.os }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🎉 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: ✨ Install dependencies
        run: |
          corepack enable
          make install
      
      - name: 📦️ Build for production
        run: make build

      - name: ✅ Check code style
        run: make check

      - name: 🧪 Test components
        run: make test
